### ISSUE TITLE
Issue with widget and  Public link

### ISSUE THREAD

**Issue by rossman22590** [webwhiz-ai/webwhiz#102]
Public Link to Chat Interface
Share the chat interface with anyone with the below unique link.

The embeded chat widget works but this and the iframe do not , any ideas? I use docker

**Comment by rossman22590** [comment]
im using widget launched with docker

**Comment by rossman22590** [comment]
successfully started +2ms
webwhiz-main-python_worker-1  | [2023-10-08 23:00:21,637: INFO/MainProcess] mingle: all alone
webwhiz-main-python_worker-1  | [2023-10-08 23:00:21,643: INFO/MainProcess] celery@6f779652facd ready.
webwhiz-main-widget-1         | 172.23.0.1 - - [08/Oct/2023:23:00:28 +0000] "GET /?kbId=65224bdb47ab506d6bed3c4a&embed=true&hide-chat-actions=true HTTP/1.1" 200 27778 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "73.143.175.253"
webwhiz-main-widget-1         | 172.23.0.1 - - [08/Oct/2023:23:00:28 +0000] "GET /index.983987c2.css HTTP/1.1" 200 10644 "https://my-botcraft-widget.ngrok.io/?kbId=65224bdb47ab506d6bed3c4a&embed=true&hide-chat-actions=true" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "73.143.175.253"
webwhiz-main-widget-1         | 172.23.0.1 - - [08/Oct/2023:23:00:28 +0000] "GET /index.983987c2.css.map HTTP/1.1" 200 34158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "73.143.175.253"
webwhiz-main-widget-1         | 172.23.0.1 - - [08/Oct/2023:23:00:28 +0000] "GET /favicon.ico HTTP/1.1" 200 27778 "https://my-botcraft-widget.ngrok.io/?kbId=65224bdb47ab506d6bed3c4a&embed=true&hide-chat-actions=true" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "73.143.175.253"
webwhiz-main-mongodb-1        | {"t":{"$date":"2023-10-08T23:00:31.006+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.6:48510","uuid":{"uuid":{"$uuid":"50420e41-64bf-4858-be60-75b8390275c6"}},"connectionId":7,"connectionCount":7}}
webwhiz-main-mongodb-1        | {"t":{"$date":"2023-10-08T23:00:31.006+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn7","msg":"client metadata","attr":{"remote":"172.23.0.6:48510","client":"conn7","doc":{"driver":{"name":"nodejs","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"Node.js v18.18.0, LE (unified)|Node.js v18.18.0, LE (unified)"}}} 
webwhiz-main-mongodb-1        | {"t":{"$date":"2023-10-08T23:00:31.465+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.5:60672","uuid":{"uuid":{"$uuid":"99134608-4d79-4353-bae0-94f274a85d27"}},"connectionId":8,"connectionCount":8}}
webwhiz-main-mongodb-1        | {"t":{"$date":"2023-10-08T23:00:31.465+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn8","msg":"client metadata","attr":{"remote":"172.23.0.5:60672","client":"conn8","doc":{"driver":{"name":"nodejs","version":"5.1.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"Node.js v18.18.0, LE (unified)|Node.js v18.18.0, LE (unified)"}}} 
webwhiz-main-widget-1         | 172.23.0.1 - - [08/Oct/2023:23:01:46 +0000] "GET /?kbId=65224bdb47ab506d6bed3c4a&embed=true&hide-chat-actions=true HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "73.143.175.253"

**Comment by rossman22590** [comment]
any ideas?

**Comment by rossman22590** [comment]
Ok I put it back online for you to see

**Comment by rossman22590** [comment]
https://my-botcraft-beta.ngrok.io/

**Comment by sachinchoolur** [comment]
Have you modified the widget source code?  There is a space after the base URL in the `chat_widget_data` API

![CleanShot 2023-10-17 at 08 18 32@2x](https://github.com/webwhiz-ai/webwhiz/assets/6586706/ed3e669b-66d5-4505-b0db-f4156e5e4395)

**Comment by rossman22590** [comment]
var __WEBWHIZ__URL = __WEBWHIZ__getWidgetURL();

function __WEBWHIZ__ready(fn) {
  if (document.readyState !== "loading") {
    fn();
    return;
  }
  document.addEventListener("DOMContentLoaded", fn);
}


const widgetStyle = `
.webwhiz-widget {
  position: fixed;
  z-index: 9999999;
  max-height: calc(100% - 30px);
  right: 20px;
  bottom: 20px;
  min-width: 80px;
  height: 80px;
  width: 80px;
  max-width: calc(100% - 40px);
}
.webwhiz-widget.wb-align-left {
  left: 0;
  right: auto;
}
.webwhiz-widget.wb-expand {
  width: 416px;
  height: 610px;
  min-width: 370px;
}
.webwhiz-widget.wb-maximize {
  width: 50%;
  height: calc(100% - 30px)
}
@media only screen and (device-width: 768px),
       only screen and (max-width: 768px){
  .webwhiz-widget.wb-maximize {
    width: 100%;
    height: 100%;
  }
  .webwhiz-widget {
    right: 0;
    bottom: 0;
  }
  .webwhiz-widget.wb-expand {
    width: 100%;
    height: 100%;
    min-width: 0;
    left: 0;
    right: 10px;
    bottom: 10px;
    top: 0;
    max-width: 100%;
    max-height: 100%;
  }
}
.webwhiz__msg-popup {
  position: fixed;
  bottom: 106px;
  max-width: fit-content;
  display: flex;
  flex-direction: column;
  max-width: 320px;
  opacity: 0;
  align-items: end;
  transition: all 0.3s ease-in-out;
  transform: translate3d(0px, 10px, 0px);
}
.webwhiz__msg-popup.webwhiz__msg-popup-left {
  left: 20px;
}
.webwhiz__msg-popup.webwhiz__msg-popup-right {
  right: 20px;
}
.webwhiz__msg-popup.webwhiz__msg-popup--show {
  opacity: 1;
  transform: translate3d(0px, 0px, 0px);
}

.webwhiz__msg-popup-item {
  padding: 20px;
  background-color: #FFF;
  display: inline-flex;
  width: auto;
  margin: 5px 0;
  font-size: 14px;
  border-radius: 6px;
  line-height: 1.5;
  color: #333;
  box-shadow: 0 2px 6px rgba(0, 0, 0, 0.08);
}
.webwhiz__msg-popup-close-btn {
  cursor: pointer;
  border-radius: 12px;
  background-color: #fff;
  font-size: 12px;
  color: rgba(0,0,0,0.65);
  border: 1px solid rgba(0,0,0,0.18);
  opacity: 0;
  width: 22px;
  height: 22px;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  transition: opacity 0.3s ease-in-out;
}

.webwhiz__msg-popup-close-btn svg {
  width: 14px;
  height: 14px;
  flex-shrink: 0;
}

.webwhiz__msg-popup:hover .webwhiz__msg-popup-close-btn {
  opacity: 0.8;
}
.webwhiz__msg-popup .webwhiz__msg-popup-close-btn:hover {
  opacity: 1;
}
`


function __WEBWHIZ__addIframe() {
  var ifrm = document.createElement("iframe");
  const kbId = __WEBWHIZ__getChatbotId();
  ifrm.setAttribute("class", "webwhiz-widget");
  ifrm.setAttribute("id", "webwhiz-widget");
  ifrm.setAttribute("data-powered-by", "https://www.webwhiz.ai/");
  ifrm.setAttribute("frameborder", "0");

  const scriptEl = document.getElementById("__webwhizSdk__");
  const container = scriptEl.getAttribute('container') || scriptEl.getAttribute('data-container');


  if (container) {
    const $container = document.querySelector(container);
    if ($container) {
      $container.appendChild(ifrm);
    }
  } else {
    var styleSheet = document.createElement('style');
    styleSheet.innerText = widgetStyle;
    document.head.appendChild(styleSheet);
    document.body.appendChild(ifrm);
  }

  const baseUrl = __WEBWHIZ__getBaseURL();
  ifrm.setAttribute("src", __WEBWHIZ__URL + '?kbId=' + kbId +'&baseUrl=' + baseUrl);
  return ifrm;
}

function addPopup(config) {
  const welcomeMessagesHTML = config.welcomeMessages.map(msg => {
      return `<div class="webwhiz__msg-popup-item">${msg}</div>`
  }).join(''); 
  const closeBtn = `<button class="webwhiz__msg-popup-close-btn" id="webwhiz__msg-popup-close-btn">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
  </button>`
  let popupPositionClass = ''
  if(config.position === 'left') {
    popupPositionClass = 'webwhiz__msg-popup-left'
  } else {
    popupPositionClass = 'webwhiz__msg-popup-right'
  }
  document.body.insertAdjacentHTML('beforeend', `<div id="webwhiz__msg-popup" class="webwhiz__msg-popup ${popupPositionClass}">${closeBtn}${welcomeMessagesHTML}</div>`);
  document.getElementById('webwhiz__msg-popup-close-btn').onclick = () => {
    removePopup();
  }
  setTimeout(() => {
    const popup = document.getElementById('webwhiz__msg-popup');
    if(popup) {
      popup.classList.add('webwhiz__msg-popup--show');
    }
  }, config.popupDelay || 3000);
}

function removePopup() {
  const popup = document.getElementById('webwhiz__msg-popup');
  if(popup) {
    popup.classList.remove('webwhiz__msg-popup--show');
    localStorage.setItem("webwhiz__popupRemoved", 'true');
    setTimeout(() => {
      popup.remove();
    }, 350);
  }
}

function __WEBWHIZ__getEventHandler(ifrm) {
  const iframe = document.getElementById("webwhiz-widget");
  const scriptEl = document.getElementById("__webwhizSdk__");
  const container = scriptEl.getAttribute('container') || scriptEl.getAttribute('data-container');
  function webWhizEventHandler(e) {
    if (e.data === "webwhiz:widget_expand") {
      iframe.classList.add("wb-expand");
      removePopup();
    } else if (e.data === "webwhiz:widget_collapse") {
      setTimeout(() => {
        iframe.classList.remove("wb-expand", "wb-maximize");
      }, 350);
    } else if (e.data === "webwhiz:widget_maximize") {
      iframe.classList.add("wb-maximize");
    } else if (e.data === "webwhiz:widget_minimize") {
      iframe.classList.remove("wb-maximize");
    } else if (e.data && e.data.messageType === 'webwhiz:widget_config') {
      const config = e.data.config || {};
      if (config.position === 'left'){
        iframe.classList.add("wb-align-left");
      }
      const popupRemoved = localStorage.getItem("webwhiz__popupRemoved");
      if(!popupRemoved && config.showAsPopup && config.welcomeMessages && config.welcomeMessages.length > 0 && !container) {
        addPopup(config);
      }
    } else if (e.data === "webwhiz:widget_clear_history") {
      localStorage.removeItem('chatHistory');
      localStorage.removeItem('sessionId');
      e.source.postMessage({ messageType: 'webwhiz:recieve_session_id', sessionId: '' }, '*');
    } else if (e.data === "webwhiz:request_meta_data") {
      const scriptEl = document.getElementById("__webwhizSdk__");
      const container = scriptEl.getAttribute('container') || scriptEl.getAttribute('data-container');
      e.source.postMessage({ messageType: 'webwhiz:recieve_meta_data', url: window.location.href, container: container }, '*');
    } else if (e.data === "webwhiz:request_chat_data") {
      const chatHistoryData = localStorage.getItem("chatHistory");
      const chatHistory = JSON.parse(chatHistoryData || '[]');
      e.source.postMessage({ messageType: 'webwhiz:recieve_chat_data', chatHistory: chatHistory }, '*');
    } else if (e.data === "webwhiz:request_session_id") {
      const sessionId = localStorage.getItem("sessionId");
      e.source.postMessage({ messageType: 'webwhiz:recieve_session_id', sessionId: sessionId }, '*');
    } else if(e.data && e.data.messageType === 'webwhiz:recieve_new_message') {
      const chatHistoryData = localStorage.getItem("chatHistory");
      let chatHistory = JSON.parse(chatHistoryData || '[]');
      const msg = e.data.message || []
      chatHistory = [...chatHistory, ...msg];
      localStorage.setItem("chatHistory", JSON.stringify(chatHistory));
    } else if(e.data && e.data.messageType === 'webwhiz:recieve_new_session_id') {
      localStorage.setItem("sessionId", e.data.sessionId);
    }
  }

  return webWhizEventHandler;
}

function __WEBWHIZ__addEventListeners(ifrm) {
  window.onmessage = __WEBWHIZ__getEventHandler(ifrm);
}

function __WEBWHIZ__getChatbotId() {
  const scriptEl = document.getElementById("__webwhizSdk__");
  const chatbotId = scriptEl.getAttribute('chatbotId') || scriptEl.getAttribute('data-chatbot-id');
  return chatbotId;
}

function __WEBWHIZ__getWidgetURL() {
  const scriptEl = document.getElementById("__webwhizSdk__");
  const baseURL = scriptEl.getAttribute('widgetUrl') || scriptEl.getAttribute('data-widget-url');
  return baseURL || 'https://my-botcraft-widget.ngrok.io';
}

function __WEBWHIZ__getBaseURL() {
  const scriptEl = document.getElementById("__webwhizSdk__");
  const baseURL = scriptEl.getAttribute('baseUrl') || scriptEl.getAttribute('data-base-url');
  console.log(baseURL);
  return baseURL || 'https://my-bocraft-pro.ngrok.io';
}

__WEBWHIZ__ready(() => {
  setTimeout(() => {
    var ifrm = __WEBWHIZ__addIframe();
    __WEBWHIZ__addEventListeners(ifrm);
  }, 1000);
});

**Comment by rossman22590** [comment]
no space
here is ENV

REACT_APP_BASE_URL='https://my-bocraft-pro.ngrok.io'

**Comment by rossman22590** [comment]
i see issue here but no clue where it coming from https://my-botcraft-widget.ngrok.io/?kbId=652249a7d2cef2bcdc0676da&embed=true&hide-chat-actions=true

**Comment by rossman22590** [comment]
any update on this?

**Comment by rossman22590** [comment]
would love to use for my website, but cannot get that feature to work, let me know how i can help solve this - service is up and i showed u env

**Comment by sachinchoolur** [comment]
In the widget HTML file, there is an unwanted space. 

Go to the view source and search for `"https://my-bocraft-pro.ngrok.io "`

To fix the issue, you can simply pass the baseUrl via query param. Below is the working link 

https://my-botcraft-widget.ngrok.io/?kbId=652249a7d2cef2bcdc0676da&embed=true&hide-chat-actions=true&baseUrl=https://my-bocraft-pro.ngrok.io

**Comment by rossman22590** [comment]
thanks! worked
