### ISSUE TITLE
Render Markdown

### ISSUE THREAD

**Issue by atraining** [webwhiz-ai/webwhiz#138]
The answers do include markdown and it should been rendered so it look like:

To install the Konfuzio SDK, follow these steps:
1. Sign up for a free account on the Konfuzio Server [here](https://app.konfuzio.com/accounts/signup/).
2. Install the `konfuzio_sdk` package by running the following command in your terminal: ``` pip install konfuzio_sdk ``` If you want to install the full instance of the SDK with AI-related components, use the following command: ``` pip install konfuzio_sdk[ai] ``` Note: The full instance cannot be installed on MacOS machines with an ARM-based chip from the M-series. In that case, you can only install the lightweight instance.
3. Initialize the package in your working directory by running the following command: ``` konfuzio_sdk init ``` This will prompt you to enter your credentials to access the Konfuzio Server. Once you provide the credentials, a `.env` file will be created in your working directory.
4. Download the data from your Konfuzio project by specifying the Project ID. Use the following command: ``` konfuzio_sdk export_project <project_id> ``` Replace `<project_id>` with the ID of your project. The data will be downloaded to a folder called `data_<project_id>`. That's it! You have successfully installed the Konfuzio SDK. You can now use it to interact with the Konfuzio Server and work with your project data.

status quo:

<img width="459" alt="msedge_O1TacoGAFP" src="https://github.com/webwhiz-ai/webwhiz/assets/2879188/03e8db6e-04bd-452a-9b01-358f7ffd47fb">

**Comment by sachinchoolur** [comment]
It works fine on the actual chatbot. We haven't added markdown support in the try chatbot section.

See the attached screenshot 

<img width="704" alt="CleanShot 2023-12-27 at 15 26 38@2x" src="https://github.com/webwhiz-ai/webwhiz/assets/6586706/8a1d796c-d979-4f29-acfc-ca3328d6677e">

**Comment by atraining** [comment]
Hi @sachinchoolur many thanks for this quick turnaround! I can confirm the Markdown rendering works in the live chat.

<img width="924" alt="msedge_oPCOV1abCw" src="https://github.com/webwhiz-ai/webwhiz/assets/2879188/52ae60ef-7a2f-4089-b950-e87e829991d1">


<img width="932" alt="msedge_YoIoU4WubY" src="https://github.com/webwhiz-ai/webwhiz/assets/2879188/d985fd48-8816-4899-855e-12f67e1bec9f">
