### ISSUE TITLE
Webwhiz Configuration help needed

### ISSUE THREAD

**Issue by b1onix** [webwhiz-ai/webwhiz#146]
### Discussed in https://github.com/webwhiz-ai/webwhiz/discussions/145

<div type='discussions-op-text'>

<sup>Originally posted by **b1onix** January 21, 2024</sup>
Hi there webwhiz community,
i'm kind of having an issue when i try to deploy webwhiz onto my Ubuntu VPS, i deployed it with docker and and when i signin and create a chatbot, and try putting the <script> tag onto my website, the chatbot doesn't show up.. since i deployed onto my subdomain, i put widgeturl (subdomain:port) into the <script> tag but it doesn't work, any assistance would be much appreciated.</div>

**Comment by hrithikt** [comment]
> ### Discussed in #145
> Originally posted by **b1onix** January 21, 2024 Hi there webwhiz community, i'm kind of having an issue when i try to deploy webwhiz onto my Ubuntu VPS, i deployed it with docker and and when i signin and create a chatbot, and try putting the <script> tag onto my website, the chatbot doesn't show up.. since i deployed onto my subdomain, i put widgeturl (subdomain:port) into the <script> tag but it doesn't work, any assistance would be much appreciated.

Hi @b1onix ,

Could you check whether you are able to access the bot using the 'Public Chat Interface'?

**Comment by hrithikt** [comment]
Closing this issue as there is already a discussion thread(#145) present.
