### ISSUE TITLE
Backend Inaccessible

### ISSUE THREAD

**Issue by IICommitII** [webwhiz-ai/webwhiz#17]
Great work with WebWhiz. I just set it up by following all docker instructions, however, I am unable to access the backend. 

Sorry if it's a basic question.

I keep getting this error when I visit "http://localhost:3000/" 

The error is: {"statusCode":401,"message":"Unauthorized"}

This may be related to MongoDB and Redis? But I am not sure. Can someone assist with how I can access the backend? Do I need to login to MongoDB first and if so, what's the path for the same? 

I would greatly appreciate your help,
Thank you!

**Comment by sachinchoolur** [comment]
Hey, sorry for the late reply. 

This is expected. You cannot call the backend directly from the browser since we need the authorization header to get the response. 
Try running UI instead, which is available at http://localhost:3030
