### ISSUE TITLE
Embedding self hosting + Default Plan

### ISSUE THREAD

**Issue by rossman22590** [webwhiz-ai/webwhiz#20]
1. Embedding seems not to work at all when put on my site. 
2. make embedding free and remove lemonsqueezy , how do I do this, or make every user default to pro on creation.

**Comment by rossman22590** [comment]
why would the embed part not work? any idea?

**Comment by sachinchoolur** [comment]
There is a minor configuration issue with self-hosting. We are working on it, and it will be ready by today EOD
more info - https://github.com/webwhiz-ai/webwhiz/issues/24

**Comment by rossman22590** [comment]
how do i make everyone pro?

**Comment by rossman22590** [comment]
by default

**Comment by sachinchoolur** [comment]
We are adding a config to set the default user type using `.env` variables. 

BTW, the self-hosting version can not be distributed, If you want to resell, you need a reseller license

**Comment by rossman22590** [comment]
yes i just dont wanna have to pay to use my own platform :) i want my team to be Premium :)

**Comment by rossman22590** [comment]
thanks for the plan variable.
