### ISSUE TITLE
Typo in "Offlne message" should be "Offline message"

### ISSUE THREAD

**Issue by zypriafl** [webwhiz-ai/webwhiz#207]
See
https://github.com/webwhiz-ai/webwhiz/blob/54266b7f0bb3c417c0b32bf0bf0cbe532422ffb0/frontend/src/utils/commonUtils.ts#L104

**Comment by hrithikt** [comment]
@zypriafl thanks for reporting the issue. the issue has been fixed with commit 1dc389101c0e881ba59229429e6ebde70150a0c8
