### ISSUE TITLE
both front end and backend use port 3000

### ISSUE THREAD

**Issue by Wladefant** [webwhiz-ai/webwhiz#213]
When doing the dev setup locally, frontend and backend want to use the same port 3000. 

```bash
yarn install
yarn start:dev
yarn crawler:worker
```

**Comment by hrithikt** [comment]
as a work around use a different port other than 3000 for running frontend.

`PORT=3001 yarn run start`

**Comment by hrithikt** [comment]
made the changes in commit d1cc6675846e0d0527228dbbd08b61943bd59d6f. closing the issue.

**Comment by Wladefant** [comment]
Yeah sure was doing that

> as a work around use a different port other than 3000 for running frontend.
> 
> `PORT=3001 yarn run start`
