### ISSUE TITLE
Use only yarn or npm

### ISSUE THREAD

**Issue by runephilosof-abtion** [webwhiz-ai/webwhiz#218]
Having two lock files means a risk of them getting out of sync.
They are probably out of sync now, since 9a9bb36b0453bc7a67e429daaac9974eebbe5140 and 5d73dd263aecff09e5031159ec841637279af9d1 changed only `yarn.lock`.

`package-lock.json` was removed in https://github.com/webwhiz-ai/webwhiz/pull/159, but was then readded in https://github.com/webwhiz-ai/webwhiz/pull/163.

The Dockerfile uses `yarn install`. So probably `package-lock.json` should be removed.

But `frontend` and `workers` folders both use `npm install` and do not have `yarn.lock`...

**Comment by hrithikt** [comment]
removed package-lock.json (05bfded12ebd2fbe6ecc3b2b5a27085998243c6d)
