### ISSUE TITLE
[Self-Hosted via docker] Still requires subscription and cannot crawl from my website for being "free" user

### ISSUE THREAD

**Issue by sebastian0619** [webwhiz-ai/webwhiz#24]
Hi, Is it due to my error that caused the captioned?

**Comment by sebastian0619** [comment]
I successfully deploy through docker and configured my apis. The purpose is to have this opensourced webbot project deployed to my website. But turns out it still requires the subscription even i have my own openai api key

**Comment by sachinchoolur** [comment]
Could you please share a screenshot of the issue? 
We are making this configurable, but for now, you can edit the below file to configure the number of projects and tokens if you need 

https://github.com/webwhiz-ai/webwhiz/blob/8e610eb5bb7c26084eeca4e214dec0bcb88078f4/src/subscription/subscription.const.ts#L23

**Comment by sebastian0619** [comment]
> 

Thx for the prompt response!

Tried tweaked the subscription.const.ts and it works! thanks.

The current problem is that, the created chatbot cannot be implemented on my website as it saids that it is not available for "Free" plan user.

![image](https://github.com/webwhiz-ai/webwhiz/assets/39752847/6f379394-31f8-4204-9344-1cf324527a17)

**Comment by sachinchoolur** [comment]
There is a minor configuration issue. We'll deploy a new version by EOD.

Until then, you can directly use the below js to add a chatbot to your website. 

```html
<script id="__webwhizSdk__" widgetUrl="WIDGET_URL/index.html" baseUrl="API_BASE_URL" src="https://www.unpkg.com/webwhiz@1.0.0/dist/sdk.js" chatbotId="YOUR_CHATBOT_ID"></script>
```
Example values 

```
baseUrl : https://api.webwhiz.ai

widgetUrl: https://widget.webwhiz.ai/
```

Please note that the widget is not included in the docker, and you need to host it separately for now.

```
https://github.com/webwhiz-ai/webwhiz/tree/main/widget
```

**Comment by sebastian0619** [comment]
> There is a minor configuration issue. We'll deploy a new version by EOD.
> 
> 
> 
> Until then, you can directly use the below js to add a chatbot to your website. 
> 
> 
> 
> ```html
> 
> <script id="__webwhizSdk__" widgetUrl="WIDGET_URL/index.html" baseUrl="API_BASE_URL" src="https://www.unpkg.com/webwhiz@1.0.0/dist/sdk.js" chatbotId="YOUR_CHATBOT_ID"></script>
> 
> ```
> 
> Example values 
> 
> 
> 
> ```
> 
> baseUrl : https://api.webwhiz.ai
> 
> 
> 
> widgetUrl: https://widget.webwhiz.ai/
> 
> ```
> 
> 
> 
> Please note that the widget is not included in the docker, and you need to host it separately for now.
> 
> 
> 
> ```
> 
> https://github.com/webwhiz-ai/webwhiz/tree/main/widget
> 
> ```
> 
> 
> 
> 

Hi Thabks for sharing the way.

I used mongodb changing my subscription plan and make my way to add to site section.

But new problem with connectivity with openai. Tried multiple times as I have many other Project hosting one same server which have no problem with openai. I'll further test it and see if there is a real problem.

Thanks

**Comment by rossman22590** [comment]
will the widget text to copy update  to 

**<script id="__webwhizSdk__" widgetUrl="WIDGET_URL/index.html" baseUrl="API_BASE_URL" src="https://www.unpkg.com/webwhiz@1.0.0/dist/sdk.js" chatbotId="YOUR_CHATBOT_ID"></script>** 

or will it remain

**<script id="__webwhizSdk__" src="https://widget.webwhiz.ai/webwhiz-sdk.js" chatbotId="64cd8d1466a32f1cf650434f"></script>**

**Comment by sachinchoolur** [comment]
If you are self-hosting, you need to provide `widgetUrl` and `baseUrl `

Docs
- Self-hosting https://www.webwhiz.ai/self-hosting/#installation
- Adding chatbot to website - https://github.com/webwhiz-ai/sdk#self-hosted-configuration

**Comment by rossman22590** [comment]
I will check this ty
