### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Bachstelze** [webwhiz-ai/webwhiz#9]
Where can I find the documentation for the code in this repo?

**Comment by analogpvt** [comment]
(venv) root@sitegpt:~/webwhiz# pm2 start ecosystem.config.js
[PM2] Applying action restartProcessId on app [celery_worker](ids: [ 0 ])
[PM2] [celery_worker](0) ✓
[PM2][WARN] Applications web, crawler_worker not running, starting...
[PM2][ERROR] Error: Script not found: /root/webwhiz/dist/main.js
[PM2][ERROR] Error: Script not found: /root/webwhiz/dist/crawler.main.js
(venv) root@sitegpt:~/webwhiz#

**Comment by analogpvt** [comment]
showing this error

**Comment by kurienzach** [comment]
Hey @Bachstelze,

Thanks for raising the issue!
There was a missing build step in the documentation. This issue has been fixed in [491d1ee](https://github.com/webwhiz-ai/webwhiz/commit/491d1eee79e9dc75054826cc2ec46a9ba4af8c38). Please try it out and let us know if this fixes the issue
